
{ Pascal Interface }
unit atmcd32d;

interface
		
const
				DRV_ERROR_CODES = 20001;
				DRV_SUCCESS = 20002;
				DRV_VXDNOTINSTALLED = 20003;
				DRV_ERROR_SCAN = 20004;
				DRV_ERROR_CHECK_SUM = 20005;
				DRV_ERROR_FILELOAD = 20006;
				DRV_UNKNOWN_FUNCTION = 20007;
				DRV_ERROR_VXD_INIT = 20008;
				DRV_ERROR_ADDRESS = 20009;
				DRV_ERROR_PAGELOCK = 20010;
				DRV_ERROR_PAGEUNLOCK = 20011;
				DRV_ERROR_BOARDTEST = 20012;
				DRV_ERROR_ACK = 20013;
				DRV_ERROR_UP_FIFO = 20014;
				DRV_ERROR_PATTERN = 20015;
				DRV_ACQUISITION_ERRORS = 20017;
				DRV_ACQ_BUFFER = 20018;
				DRV_ACQ_DOWNFIFO_FULL = 20019;
				DRV_PROC_UNKONWN_INSTRUCTION = 20020;
				DRV_ILLEGAL_OP_CODE = 20021;
				DRV_KINETIC_TIME_NOT_MET = 20022;
				DRV_ACCUM_TIME_NOT_MET = 20023;
				DRV_NO_NEW_DATA = 20024;
				DRV_PCI_DMA_FAIL =  20025;
				DRV_SPOOLERROR = 20026;
				DRV_SPOOLSETUPERROR = 20027;
				DRV_FILESIZELIMITERROR = 20028;
				DRV_ERROR_FILESAVE = 20029;
				DRV_TEMPERATURE_CODES = 20033;
				DRV_TEMPERATURE_OFF = 20034;
				DRV_TEMPERATURE_NOT_STABILIZED = 20035;
				DRV_TEMPERATURE_STABILIZED = 20036;
				DRV_TEMPERATURE_NOT_REACHED = 20037;
				DRV_TEMPERATURE_OUT_RANGE = 20038;
				DRV_TEMPERATURE_NOT_SUPPORTED = 20039;
				DRV_TEMPERATURE_DRIFT = 20040;
				DRV_TEMP_CODES = 20033;
				DRV_TEMP_OFF = 20034;
				DRV_TEMP_NOT_STABILIZED = 20035;
				DRV_TEMP_STABILIZED = 20036;
				DRV_TEMP_NOT_REACHED = 20037;
				DRV_TEMP_OUT_RANGE = 20038;
				DRV_TEMP_NOT_SUPPORTED = 20039;
				DRV_TEMP_DRIFT = 20040;
				DRV_GENERAL_ERRORS = 20049;
				DRV_INVALID_AUX = 20050;
				DRV_COF_NOTLOADED = 20051;
				DRV_FPGAPROG = 20052;
				DRV_FLEXERROR = 20053;
				DRV_GPIBERROR = 20054;
				DRV_EEPROMVERSIONERROR = 20055;
				DRV_DATATYPE = 20064;
				DRV_DRIVER_ERRORS = 20065;
				DRV_P1INVALID = 20066;
				DRV_P2INVALID = 20067;
				DRV_P3INVALID = 20068;
				DRV_P4INVALID = 20069;
				DRV_INIERROR = 20070;
				DRV_COFERROR = 20071;
				DRV_ACQUIRING = 20072;
				DRV_IDLE = 20073;
				DRV_TEMPCYCLE = 20074;
				DRV_NOT_INITIALIZED = 20075;
				DRV_P5INVALID = 20076;
				DRV_P6INVALID = 20077;
				DRV_INVALID_MODE = 20078;
				DRV_INVALID_FILTER = 20079;
				DRV_I2CERRORS = 20080;
				DRV_I2CDEVNOTFOUND = 20081;
				DRV_I2CTIMEOUT = 20082;
				DRV_P7INVALID = 20083;
				DRV_P8INVALID = 20084;
				DRV_P9INVALID = 20085;
				DRV_P10INVALID = 20086;
				DRV_USBERROR = 20089;
				DRV_IOCERROR = 20090;
				DRV_VRMVERSIONERROR = 20091;
				DRV_USB_INTERRUPT_ENDPOINT_ERROR = 20093;
				DRV_RANDOM_TRACK_ERROR = 20094;
				DRV_INVALID_TRIGGER_MODE = 20095;
				DRV_LOAD_FIRMWARE_ERROR = 20096;
				DRV_DIVIDE_BY_ZERO_ERROR = 20097;
				DRV_INVALID_RINGEXPOSURES = 20098;
				DRV_BINNING_ERROR = 20099;
				DRV_INVALID_AMPLIFIER = 20100;
				DRV_ERROR_NOCAMERA = 20990;
				DRV_NOT_SUPPORTED = 20991;
				DRV_NOT_AVAILABLE = 20992;
				DRV_ERROR_MAP = 20115;
				DRV_ERROR_UNMAP = 20116;
				DRV_ERROR_MDL = 20117;
				DRV_ERROR_UNMDL = 20118;
				DRV_ERROR_BUFFSIZE = 20119;
				DRV_ERROR_NOHANDLE = 20121;
				DRV_GATING_NOT_AVAILABLE = 20130;
				DRV_FPGA_VOLTAGE_ERROR = 20131;
				DRV_OW_CMD_FAIL = 20150;
				DRV_OWMEMORY_BAD_ADDR = 20151;
				DRV_OWCMD_NOT_AVAILABLE = 20152;
				DRV_OW_NO_SLAVES = 20153;
				DRV_OW_NOT_INITIALIZED = 20154;
				DRV_OW_ERROR_SLAVE_NUM = 20155;
				DRV_MSTIMINGS_ERROR = 20156;
				DRV_OA_NULL_ERROR = 20173;
				DRV_OA_PARSE_DTD_ERROR = 20174;
				DRV_OA_DTD_VALIDATE_ERROR = 20175;
				DRV_OA_FILE_ACCESS_ERROR = 20176;
				DRV_OA_FILE_DOES_NOT_EXIST = 20177;
				DRV_OA_XML_INVALID_OR_NOT_FOUND_ERROR = 20178;
				DRV_OA_PRESET_FILE_NOT_LOADED = 20179;
				DRV_OA_USER_FILE_NOT_LOADED = 20180;
				DRV_OA_PRESET_AND_USER_FILE_NOT_LOADED = 20181;
				DRV_OA_INVALID_FILE = 20182;
				DRV_OA_FILE_HAS_BEEN_MODIFIED = 20183;
				DRV_OA_BUFFER_FULL = 20184;
				DRV_OA_INVALID_STRING_LENGTH = 20185;
				DRV_OA_INVALID_CHARS_IN_NAME = 20186;
				DRV_OA_INVALID_NAMING = 20187;
				DRV_OA_GET_CAMERA_TYPE_ERROR = 20188;
				DRV_OA_MODE_ALREADY_EXISTS = 20189;
				DRV_OA_STRINGS_NOT_EQUAL = 20190;
				DRV_OA_NO_USER_DATA = 20191;
				DRV_OA_VALUE_NOT_SUPPORTED = 20192;
				DRV_OA_MODE_DOES_NOT_EXIST = 20193;
				
		
	  {AT_SDKVersion Definitions}
		AT_SDKVersion = $40000000;
	  {AT_DeviceDriverVersion Definitions}
		AT_DeviceDriverVersion = $40000001;
	  { NOTE: Update the count when you add entries }
    AT_NoOfVersionInfoIds  = 2;
			
		
	  {AT_DDGLite_ChannelA Definitions}
		AT_DDGLite_ChannelA = $40000000;
	  {AT_DDGLite_ChannelB Definitions}
		AT_DDGLite_ChannelB = $40000001;
	  {AT_DDGLite_ChannelC Definitions}
		AT_DDGLite_ChannelC = $40000002;
				
    AT_DDGLite_ControlBit_GlobalEnable   = $01;

    AT_DDGLite_ControlBit_ChannelEnable  = $01;
    AT_DDGLite_ControlBit_FreeRun        = $02;
    AT_DDGLite_ControlBit_DisableOnFrame = $04;
    AT_DDGLite_ControlBit_RestartOnFire  = $08;
    AT_DDGLite_ControlBit_Invert         = $10;
    AT_DDGLite_ControlBit_EnableOnFire   = $20;
          
	  type
      AndorCapabilities = Record
	     ulSize: Integer;
			ulAcqModes: Integer;
			ulReadModes: Integer;
			ulTriggerModes: Integer;
			ulCameraType: Integer;
			ulPixelMode: Integer;
			ulSetFunctions: Integer;
			ulGetFunctions: Integer;
			ulFeatures: Integer;
			ulPCICard: Integer;
			ulEMGainCapability: Integer;
			ulFTReadModes: Integer;
	  end;
	  
	  type
      ColorDemosaicInfo = Record
	     iX: Integer;
			iY: Integer;
			iAlgorithm: Integer;
			iXPhase: Integer;
			iYPhase: Integer;
			iBackground: Integer;
	  end;
	  
	  type
      WhiteBalanceInfo = Record
	     iSize: Integer;
			iX: Integer;
			iY: Integer;
			iAlgorithm: Integer;
			iROI_left: Integer;
			iROI_right: Integer;
			iROI_top: Integer;
			iROI_bottom: Integer;
			iOperation: Integer;
	  end;
	  
	  function AbortAcquisition(): integer; stdcall;
	  function CancelWait(): integer; stdcall;
	  function CoolerOFF(): integer; stdcall;
	  function CoolerON(): integer; stdcall;
	  function DemosaicImage(grey: PWord; red: PWord; green: PWord; blue: PWord; info: ColorDemosaicInfo): integer; stdcall;
	  function EnableKeepCleans(iMode: Integer): integer; stdcall;
	  function FreeInternalMemory(): integer; stdcall;
	  function GetAcquiredData(arr: PInteger; size: Integer): integer; stdcall;
	  function GetAcquiredData16(arr: PWord; size: Integer): integer; stdcall;
	  function GetAcquiredFloatData(arr: PSingle; size: Integer): integer; stdcall;
	  function GetAcquisitionProgress(var acc: Integer; var series: Integer): integer; stdcall;
	  function GetAcquisitionTimings(var exposure: Single; var accumulate: Single; var kinetic: Single): integer; stdcall;
	  function GetAdjustedRingExposureTimes(inumTimes: Integer; var fptimes: Single): integer; stdcall;
	  function GetAllDMAData(arr: PInteger; size: Integer): integer; stdcall;
	  function GetAmpDesc(index: Integer; name: PChar; length: Integer): integer; stdcall;
	  function GetAmpMaxSpeed(index: Integer; var speed: Single): integer; stdcall;
	  function GetAvailableCameras(var totalCameras: Integer): integer; stdcall;
	  function GetBackground(arr: PInteger; size: Integer): integer; stdcall;
	  function GetBitDepth(channel: Integer; var depth: Integer): integer; stdcall;
	  function GetCameraEventStatus(var camStatus: Integer): integer; stdcall;
	  function GetCameraHandle(cameraIndex: Integer; var cameraHandle: Integer): integer; stdcall;
	  function GetCameraInformation(index: Integer; var information: Integer): integer; stdcall;
	  function GetCameraSerialNumber(var number: Integer): integer; stdcall;
	  function GetCapabilities(caps: AndorCapabilities): integer; stdcall;
	  function GetControllerCardModel(controllerCardModel: PChar): integer; stdcall;
	  function GetCurrentCamera(var cameraHandle: Integer): integer; stdcall;
	  function GetCYMGShift(var iXshift: Integer; var iYShift: Integer): integer; stdcall;
	  function GetDDGExternalOutputEnabled(uiIndex: Integer; puiEnabled: PInteger): integer; stdcall;
	  function GetDDGExternalOutputPolarity(uiIndex: Integer; puiPolarity: PInteger): integer; stdcall;
	  function GetDDGExternalOutputStepEnabled(uiIndex: Integer; puiEnabled: PInteger): integer; stdcall;
	  function GetDDGExternalOutputTime(uiIndex: Integer; puiDelay: Integer; puiWidth: Integer): integer; stdcall;
	  function GetDDGGateTime(puiDelay: Integer; puiWidth: Integer): integer; stdcall;
	  function GetDDGInsertionDelay(piState: PInteger): integer; stdcall;
	  function GetDDGIntelligate(piState: PInteger): integer; stdcall;
	  function GetDDGIOC(state: PInteger): integer; stdcall;
	  function GetDDGIOCFrequency(var frequency: Double): integer; stdcall;
	  function GetDDGIOCNumber(var numberPulses: Integer): integer; stdcall;
	  function GetDDGIOCNumberRequested(pulses: PInteger): integer; stdcall;
	  function GetDDGIOCPeriod(var period: Integer): integer; stdcall;
	  function GetDDGIOCPulses(var pulses: Integer): integer; stdcall;

	{ DDG Lite functions }
	  function GetDDGLiteGlobalControlByte(control: PByte): integer; stdcall;
	  function GetDDGLiteControlByte(channel: Integer; control: PByte): integer; stdcall;
	  function GetDDGLiteInitialDelay(channel: Integer; fDelay: PSingle): integer; stdcall;
	  function GetDDGLitePulseWidth(channel: Integer; fWidth: PSingle): integer; stdcall;
	  function GetDDGLiteInterPulseDelay(channel: Integer; fDelay: PSingle): integer; stdcall;
	  function GetDDGLitePulsesPerExposure(channel: Integer; ui32Pulses: PInteger): integer; stdcall;

	  function GetDDGPulse(wid: Double; resolution: Double; var Delay: Double; var Width: Double): integer; stdcall;
	  function GetDDGStepCoefficients(mode: Integer; p1: Double; p2: Double): integer; stdcall;
	  function GetDDGStepMode(mode: PInteger): integer; stdcall;
	  function GetDetector(var xpixels: Integer; var ypixels: Integer): integer; stdcall;
	  function GetDICameraInfo(info: Integer): integer; stdcall;
	  function GetEMCCDGain(var gain: Integer): integer; stdcall;
	  function GetEMGainRange(var low: Integer; var high: Integer): integer; stdcall;
	  function GetExternalTriggerTermination(puiTermination: PInteger): integer; stdcall;
	  function GetFastestRecommendedVSSpeed(var index: Integer; var speed: Single): integer; stdcall;
	  function GetFIFOUsage(var FIFOusage: Integer): integer; stdcall;
	  function GetFilterMode(var mode: Integer): integer; stdcall;
	  function GetFKExposureTime(var time: Single): integer; stdcall;
	  function GetFKVShiftSpeed(index: Integer; var speed: Integer): integer; stdcall;
	  function GetFKVShiftSpeedF(index: Integer; var speed: Single): integer; stdcall;
	  function GetFrontEndStatus(piFlag: PInteger): integer; stdcall;
	  function GetGateMode(piGatemode: PInteger): integer; stdcall;
	  function GetHardwareVersion(var PCB: Integer; var Decode: Integer; var dummy1: Integer; var dummy2: Integer; var CameraFirmwareVersion: Integer; var CameraFirmwareBuild: Integer): integer; stdcall;
	  function GetHeadModel(name: PChar): integer; stdcall;
	  function GetHorizontalSpeed(index: Integer; speed: Integer): integer; stdcall;
	  function GetHSSpeed(channel: Integer; typ: Integer; index: Integer; var speed: Single): integer; stdcall;
	  function GetHVflag(var bFlag: Integer): integer; stdcall;
	  function GetID(devNum: Integer; var id: Integer): integer; stdcall;
	  function GetImageFlip(var iHFlip: Integer; var iVFlip: Integer): integer; stdcall;
	  function GetImageRotate(var iRotate: Integer): integer; stdcall;
	  function GetImages(first: Integer; last: Integer; arr: PInteger; size: Integer; var validfirst: Integer; var validlast: Integer): integer; stdcall;
	  function GetImages16(first: Integer; last: Integer; arr: PWord; size: Integer; var validfirst: Integer; var validlast: Integer): integer; stdcall;
	  function GetImagesPerDMA(var images: Integer): integer; stdcall;
	  function GetIRQ(IRQ: PInteger): integer; stdcall;
	  function GetKeepCleanTime(var KeepCleanTime: Single): integer; stdcall;
	  function GetMaximumBinning(ReadMode: Integer; HorzVert: Integer; var MaxBinning: Integer): integer; stdcall;
	  function GetMaximumExposure(var MaxExp: Single): integer; stdcall;
	  function GetMCPGain(piGain: PInteger): integer; stdcall;
	  function GetMCPGainRange(var iLow: Integer; var iHigh: Integer): integer; stdcall;
	  function GetMCPGainTable(iNum: Integer; piGain: PInteger; pfPhotoepc: PSingle): integer; stdcall;
	  function GetMCPVoltage(var iVoltage: Integer): integer; stdcall;
	  function GetMinimumImageLength(var MinImageLength: Integer): integer; stdcall;
	  function GetMinimumNumberInSeries(var number: Integer): integer; stdcall;
	  function GetMostRecentColorImage16(size: Integer; algorithm: Integer; red: PWord; green: PWord; blue: PWord): integer; stdcall;
	  function GetMostRecentImage(arr: PInteger; size: Integer): integer; stdcall;
	  function GetMostRecentImage16(arr: PWord; size: Integer): integer; stdcall;
	  function GetMSTimingsData(TimeOfStart: Single; pfDifferences: PSingle; inoOfImages: Integer): integer; stdcall;
	  function GetMetaDataInfo(TimeOfStart: Single; pfTimeFromStart: PSingle; index: Integer): integer; stdcall;
	  function GetMSTimingsEnabled(): integer; stdcall;
	  function GetNewData(arr: PInteger; size: Integer): integer; stdcall;
	  function GetNewData16(arr: PWord; size: Integer): integer; stdcall;
	  function GetNewData8(arr: PByte; size: Integer): integer; stdcall;
	  function GetNewFloatData(arr: PSingle; size: Integer): integer; stdcall;
	  function GetNumberADChannels(var channels: Integer): integer; stdcall;
	  function GetNumberAmp(var amp: Integer): integer; stdcall;
	  function GetNumberAvailableImages(var first: Integer; var last: Integer): integer; stdcall;
	  function GetNumberDDGExternalOutputs(puiCount: PInteger): integer; stdcall;
	  function GetNumberDevices(var numDevs: Integer): integer; stdcall;
	  function GetNumberFKVShiftSpeeds(var number: Integer): integer; stdcall;
	  function GetNumberHorizontalSpeeds(var number: Integer): integer; stdcall;
	  function GetNumberHSSpeeds(channel: Integer; typ: Integer; var speeds: Integer): integer; stdcall;
	  function GetNumberNewImages(var first: Integer; var last: Integer): integer; stdcall;
	  function GetNumberPreAmpGains(var noGains: Integer): integer; stdcall;
	  function GetNumberRingExposureTimes(var ipnumTimes: Integer): integer; stdcall;
	  function GetNumberIO(var iNumber: Integer): integer; stdcall;
	  function GetNumberVerticalSpeeds(var number: Integer): integer; stdcall;
	  function GetNumberVSAmplitudes(var number: Integer): integer; stdcall;
	  function GetNumberVSSpeeds(var speeds: Integer): integer; stdcall;
	  function GetOldestImage(arr: PInteger; size: Integer): integer; stdcall;
	  function GetOldestImage16(arr: PWord; size: Integer): integer; stdcall;
	  function GetPhosphorStatus(piFlag: PInteger): integer; stdcall;
	  function GetPhysicalDMAAddress(Address1: PInteger; Address2: PInteger): integer; stdcall;
	  function GetPixelSize(var xSize: Single; var ySize: Single): integer; stdcall;
	  function GetPreAmpGain(index: Integer; var gain: Single): integer; stdcall;
	  function GetDualExposureTimes(var exposure1: Single; var exposure2: Single): integer; stdcall;
	  function GetQE(sensor: PChar; wavelength: Single; var QE: Single): integer; stdcall;
	  function GetReadOutTime(var ReadOutTime: Single): integer; stdcall;
	  function GetRegisterDump(var mode: Integer): integer; stdcall;
	  function GetRingExposureRange(var fpMin: Single; var fpMax: Single): integer; stdcall;
	  function GetSensitivity(channel: Integer; horzShift: Integer; amplifier: Integer; pa: Integer; var sensitivity: Single): integer; stdcall;
	  function GetSizeOfCircularBuffer(var index: Integer): integer; stdcall;
	  function GetSlotBusDeviceFunction(var dwslot: Integer; var dwBus: Integer; var dwDevice: Integer; var dwFunction: Integer): integer; stdcall;
	  function GetSoftwareVersion(var eprom: Integer; var coffile: Integer; var vxdrev: Integer; var vxdver: Integer; var dllrev: Integer; var dllver: Integer): integer; stdcall;
	  function GetSpoolProgress(var index: Integer): integer; stdcall;
	  function GetStartUpTime(var time: Single): integer; stdcall;
	  function GetStatus(var status: Integer): integer; stdcall;
	  function GetTECStatus(piFlag: PInteger): integer; stdcall;
	  function GetTemperature(var temperature: Integer): integer; stdcall;
	  function GetTemperatureF(var temperature: Single): integer; stdcall;
	  function GetTemperatureRange(var mintemp: Integer; var maxtemp: Integer): integer; stdcall;
	  function GetTemperatureStatus(SensorTemp: PSingle; TargetTemp: PSingle; AmbientTemp: PSingle; CoolerVolts: PSingle): integer; stdcall;
	  function GetTotalNumberImagesAcquired(var index: Integer): integer; stdcall;
	  function GetIODirection(index: Integer; var iDirection: Integer): integer; stdcall;
	  function GetIOLevel(index: Integer; var iLevel: Integer): integer; stdcall;
	  function GetVersionInfo(arr: Integer; szVersionInfo: PChar; ui32BufferLen: Integer): integer; stdcall;
	  function GetVerticalSpeed(index: Integer; var speed: Integer): integer; stdcall;
	  function GetVirtualDMAAddress(Address1: Integer; Address2: Integer): integer; stdcall;
	  function GetVSSpeed(index: Integer; var speed: Single): integer; stdcall;
	  function GPIBReceive(id: Integer; address: Single; text: PChar; size: Integer): integer; stdcall;
	  function GPIBSend(id: Integer; address: Single; text: PChar): integer; stdcall;
	  function I2CBurstRead(i2cAddress: Byte; nBytes: Integer; data: PByte): integer; stdcall;
	  function I2CBurstWrite(i2cAddress: Byte; nBytes: Integer; data: PByte): integer; stdcall;
	  function I2CRead(deviceID: Byte; intAddress: Byte; var pdata: Byte): integer; stdcall;
	  function I2CReset(): integer; stdcall;
	  function I2CWrite(deviceID: Byte; intAddress: Byte; data: Byte): integer; stdcall;
	  function IdAndorDll(): integer; stdcall;
	  function InAuxPort(port: Integer; var state: Integer): integer; stdcall;
	  function Initialize(dir: PChar): integer; stdcall;
	  function InitializeDevice(dir: PChar): integer; stdcall;
	  function IsAmplifierAvailable(iamp: Integer): integer; stdcall;
	  function IsCoolerOn(var iCoolerStatus: Integer): integer; stdcall;
	  function IsInternalMechanicalShutter(var InternalShutter: Integer): integer; stdcall;
	  function IsPreAmpGainAvailable(channel: Integer; amplifier: Integer; index: Integer; pa: Integer; var status: Integer): integer; stdcall;
	  function IsTriggerModeAvailable(iTriggerMode: Integer): integer; stdcall;
	  function Merge(arr: PInteger; nOrder: Integer; nPoint: Integer; nPixel: Integer; coeff: PSingle; fit: Integer; hbin: Integer; output: PInteger; var start: Single; var step_Renamed: Single): integer; stdcall;
	  function OutAuxPort(port: Integer; state: Integer): integer; stdcall;
	  function PrepareAcquisition(): integer; stdcall;
	  function SaveAsBmp(path: PChar; palette: PChar; ymin: Integer; ymax: Integer): integer; stdcall;
	  function SaveAsCommentedSif(path: PChar; comment: PChar): integer; stdcall;
	  function SaveAsEDF(szPath: PChar; iMode: Integer): integer; stdcall;
	  function SaveAsFITS(szFileTitle: PChar; typ: Integer): integer; stdcall;
	  function SaveAsRaw(szFileTitle: PChar; typ: Integer): integer; stdcall;
	  function SaveAsSif(path: PChar): integer; stdcall;
	  function SaveAsSPC(path: PChar): integer; stdcall;
	  function SaveAsTiff(path: PChar; palette: PChar; position: Integer; typ: Integer): integer; stdcall;
	  function SaveAsTiffEx(path: PChar; palette: PChar; position: Integer; typ: Integer; mode: Integer): integer; stdcall;
	  function SaveEEPROMToFile(cFileName: PChar): integer; stdcall;
	  function SaveToClipBoard(palette: PChar): integer; stdcall;
	  function SelectDevice(devNum: Integer): integer; stdcall;
	  function SendSoftwareTrigger(): integer; stdcall;
	  function SetAccumulationCycleTime(time: Single): integer; stdcall;
	  function SetAcqStatusEvent(statusEvent: Integer): integer; stdcall;
	  function SetAcquisitionMode(mode: Integer): integer; stdcall;
	  function SetAcquisitionType(typ: Integer): integer; stdcall;
	  function SetADChannel(channel: Integer): integer; stdcall;
	  function SetAdvancedTriggerModeState(iState: Integer): integer; stdcall;
	  function SetBackground(arr: PInteger; size: Integer): integer; stdcall;
	  function SetBaselineClamp(state: Integer): integer; stdcall;
	  function SetBaselineOffset(offset: Integer): integer; stdcall;
	  function SetCameraStatusEnable(Enable: Integer): integer; stdcall;
	  function SetComplexImage(numAreas: Integer; areas: PInteger): integer; stdcall;
	  function SetCoolerMode(mode: Integer): integer; stdcall;
	  function SetCountConvertMode(Mode: Integer): integer; stdcall;
	  function SetCountConvertWavelength(wavelength: Single): integer; stdcall;
	  function SetCropMode(active: Integer; cropHeight: Integer; reserved: Integer): integer; stdcall;
	  function SetCurrentCamera(cameraHandle: Integer): integer; stdcall;
	  function SetCustomTrackHBin(bin: Integer): integer; stdcall;
	  function SetDataType(typ: Integer): integer; stdcall;
	  function SetDACOutput(iOption: Integer; iResolution: Integer; iValue: Integer): integer; stdcall;
	  function SetDACOutputScale(iScale: Integer): integer; stdcall;
	  function SetDDGAddress(t0: Byte; t1: Byte; t2: Byte; t3: Byte; address: Byte): integer; stdcall;
	  function SetDDGExternalOutputEnabled(uiIndex: Integer; uiEnabled: Integer): integer; stdcall;
	  function SetDDGExternalOutputPolarity(uiIndex: Integer; uiPolarity: Integer): integer; stdcall;
	  function SetDDGExternalOutputStepEnabled(uiIndex: Integer; uiEnabled: Integer): integer; stdcall;
	  function SetDDGExternalOutputTime(uiIndex: Integer; uiDelay: Integer; uiWidth: Integer): integer; stdcall;
	  function SetDDGGain(gain: Integer): integer; stdcall;
	  function SetDDGGateStep(step_Renamed: Double): integer; stdcall;
	  function SetDDGGateTime(uiDelay: Integer; uiWidth: Integer): integer; stdcall;
	  function SetDDGInsertionDelay(state: Integer): integer; stdcall;
	  function SetDDGIntelligate(state: Integer): integer; stdcall;
	  function SetDDGIOC(state: Integer): integer; stdcall;
	  function SetDDGIOCFrequency(frequency: Double): integer; stdcall;
	  function SetDDGIOCNumber(numberPulses: Integer): integer; stdcall;
	  function SetDDGIOCPeriod(period: Integer): integer; stdcall;

	{ DDG Lite functions }
	  function SetDDGLiteGlobalControlByte(control: Byte): integer; stdcall;
	  function SetDDGLiteControlByte(channel: Integer; control: Byte): integer; stdcall;
	  function SetDDGLiteInitialDelay(channel: Integer; fDelay: Single): integer; stdcall;
	  function SetDDGLitePulseWidth(channel: Integer; fWidth: Single): integer; stdcall;
	  function SetDDGLiteInterPulseDelay(channel: Integer; fDelay: Single): integer; stdcall;
	  function SetDDGLitePulsesPerExposure(channel: Integer; ui32Pulses: Integer): integer; stdcall;

	  function SetDDGStepCoefficients(mode: Integer; p1: Double; p2: Double): integer; stdcall;
	  function SetDDGStepMode(mode: Integer): integer; stdcall;
	  function SetDDGTimes(t0: Double; t1: Double; t2: Double): integer; stdcall;
	  function SetDDGTriggerMode(mode: Integer): integer; stdcall;
	  function SetDDGVariableGateStep(mode: Integer; p1: Double; p2: Double): integer; stdcall;
	  function SetDelayGenerator(board: Integer; address: Single; typ: Integer): integer; stdcall;
	  function SetDMAParameters(MaxImagesPerDMA: Integer; SecondsPerDMA: Single): integer; stdcall;
	  function SetDriverEvent(driverEvent: Integer): integer; stdcall;
	  function SetEMAdvanced(state: Integer): integer; stdcall;
	  function SetEMCCDGain(gain: Integer): integer; stdcall;
	  function SetEMClockCompensation(EMClockCompensationFlag: Integer): integer; stdcall;
	  function SetEMGainMode(mode: Integer): integer; stdcall;
	  function SetExposureTime(time: Single): integer; stdcall;
	  function SetExternalTriggerTermination(uiTermination: Integer): integer; stdcall;
	  function SetFanMode(mode: Integer): integer; stdcall;
	  function SetFastExtTrigger(mode: Integer): integer; stdcall;
	  function SetFastKinetics(exposedRows: Integer; seriesLength: Integer; time: Single; mode: Integer; hbin: Integer; vbin: Integer): integer; stdcall;
	  function SetFastKineticsEx(exposedRows: Integer; seriesLength: Integer; time: Single; mode: Integer; hbin: Integer; vbin: Integer; offset: Integer): integer; stdcall;
	  function SetFilterMode(mode: Integer): integer; stdcall;
	  function SetFilterParameters(width: Integer; sensitivity: Single; range: Integer; accept: Single; smooth: Integer; noise: Integer): integer; stdcall;
	  function SetFKVShiftSpeed(index: Integer): integer; stdcall;
	  function SetFPDP(state: Integer): integer; stdcall;
	  function SetFrameTransferMode(mode: Integer): integer; stdcall;
	  function SetFrontEndEvent(driverEvent: Integer): integer; stdcall;
	  function SetFullImage(hbin: Integer; vbin: Integer): integer; stdcall;
	  function SetFVBHBin(bin: Integer): integer; stdcall;
	  function SetGain(gain: Integer): integer; stdcall;
	  function SetGate(delay: Single; width: Single; stepRenamed: Single): integer; stdcall;
	  function SetGateMode(gatemode: Integer): integer; stdcall;
	  function SetHighCapacity(state: Integer): integer; stdcall;
	  function SetHorizontalSpeed(index: Integer): integer; stdcall;
	  function SetHSSpeed(typ: Integer; index: Integer): integer; stdcall;
	  function SetImage(hbin: Integer; vbin: Integer; hstart: Integer; hend: Integer; vstart: Integer; vend: Integer): integer; stdcall;
	  function SetImageFlip(iHFlip: Integer; iVFlip: Integer): integer; stdcall;
	  function SetImageRotate(iRotate: Integer): integer; stdcall;
	  function SetIsolatedCropMode(active: Integer; cropheight: Integer; cropwidth: Integer; vbin: Integer; hbin: Integer): integer; stdcall;
	  function SetKineticCycleTime(time: Single): integer; stdcall;
	  function SetMCPGain(gain: Integer): integer; stdcall;
	  function SetMCPGating(gating: Integer): integer; stdcall;
	  function SetMessageWindow(wnd: Integer): integer; stdcall;
	  function SetMetaData(state: Integer): integer; stdcall;
	  function SetMultiTrack(number: Integer; height: Integer; offset: Integer; var bottom: Integer; var gap: Integer): integer; stdcall;
	  function SetMultiTrackHBin(bin: Integer): integer; stdcall;
	  function SetMultiTrackHRange(iStart: Integer; iEnd: Integer): integer; stdcall;
	  function SetMultiTrackScan(trackHeight: Integer; numberTracks: Integer; iSIHStart: Integer; iSIHEnd: Integer; trackHBinning: Integer; trackVBinning: Integer; trackGap: Integer; trackOffset: Integer; trackSkip: Integer; numberSubFrames: Integer): integer; stdcall;
	  function SetNextAddress(data: PInteger; lowAdd: Integer; highAdd: Integer; length: Integer; physical: Integer): integer; stdcall;
	  function SetNextAddress16(data: PInteger; lowAdd: Integer; highAdd: Integer; length: Integer; physical: Integer): integer; stdcall;
	  function SetNumberAccumulations(number: Integer): integer; stdcall;
	  function SetNumberKinetics(number: Integer): integer; stdcall;
	  function SetNumberPrescans(iNumber: Integer): integer; stdcall;
	  function SetOutputAmplifier(typ: Integer): integer; stdcall;
	  function SetOverlapMode(mode: Integer): integer; stdcall;
	  function SetPCIMode(mode: Integer; value: Integer): integer; stdcall;
	  function SetPhotonCounting(state: Integer): integer; stdcall;
	  function SetPhotonCountingThreshold(min: Integer; max: Integer): integer; stdcall;
	  function SetPhosphorEvent(driverEvent: Integer): integer; stdcall;
	  function SetPhotonCountingDivisions(noOfDivisions: Integer; divisions: PInteger): integer; stdcall;
	  function SetPixelMode(bitdepth: Integer; colormode: Integer): integer; stdcall;
	  function SetPreAmpGain(index: Integer): integer; stdcall;
	  function SetDualExposureTimes(expTime1: Single; expTime2: Single): integer; stdcall;
	  function SetDualExposureMode(mode: Integer): integer; stdcall;
	  function SetRandomTracks(numTracks: Integer; areas: Integer): integer; stdcall;
	  function SetReadMode(mode: Integer): integer; stdcall;
	  function SetRegisterDump(mode: Integer): integer; stdcall;
	  function SetRingExposureTimes(numTimes: Integer; times: PSingle): integer; stdcall;
	  function SetSaturationEvent(saturationEvent: Integer): integer; stdcall;
	  function SetShutter(typ: Integer; mode: Integer; closingtime: Integer; openingtime: Integer): integer; stdcall;
	  function SetShutterEx(typ: Integer; mode: Integer; closingtime: Integer; openingtime: Integer; extmode: Integer): integer; stdcall;
	  function SetShutters(typ: Integer; mode: Integer; closingtime: Integer; openingtime: Integer; exttype: Integer; extmode: Integer; dummy1: Integer; dummy2: Integer): integer; stdcall;
	  function SetSifComment(comment: PChar): integer; stdcall;
	  function SetSingleTrack(centre: Integer; height: Integer): integer; stdcall;
	  function SetSingleTrackHBin(bin: Integer): integer; stdcall;
	  function SetSpool(active: Integer; method: Integer; path: PChar; framebuffersize: Integer): integer; stdcall;
	  function SetStorageMode(mode: Integer): integer; stdcall;
	  function SetTECEvent(driverEvent: Integer): integer; stdcall;
	  function SetTemperature(temperature: Integer): integer; stdcall;
	  function SetTemperatureEvent(temperatureEvent: Integer): integer; stdcall;
	  function SetTriggerMode(mode: Integer): integer; stdcall;
	  function SetTriggerInvert(mode: Integer): integer; stdcall;
	  function GetTriggerLevelRange(var minimum: Single; var maximum: Single): integer; stdcall;
	  function SetTriggerLevel(f_level: Single): integer; stdcall;
	  function SetIODirection(index: Integer; iDirection: Integer): integer; stdcall;
	  function SetIOLevel(index: Integer; iLevel: Integer): integer; stdcall;
	  function SetUserEvent(userEvent: Integer): integer; stdcall;
	  function SetUSGenomics(width: Integer; height: Integer): integer; stdcall;
	  function SetVerticalRowBuffer(rows: Integer): integer; stdcall;
	  function SetVerticalSpeed(index: Integer): integer; stdcall;
	  function SetVirtualChip(state: Integer): integer; stdcall;
	  function SetVSAmplitude(index: Integer): integer; stdcall;
	  function SetVSSpeed(index: Integer): integer; stdcall;
	  function ShutDown(): integer; stdcall;
	  function StartAcquisition(): integer; stdcall;
	  function UnMapPhysicalAddress(): integer; stdcall;
	  function WaitForAcquisition(): integer; stdcall;
	  function WaitForAcquisitionByHandle(cameraHandle: Integer): integer; stdcall;
	  function WaitForAcquisitionByHandleTimeOut(cameraHandle: Integer; iTimeOutMs: Integer): integer; stdcall;
	  function WaitForAcquisitionTimeOut(iTimeOutMs: Integer): integer; stdcall;
	  function WhiteBalance(wRed: PWord; wGreen: PWord; wBlue: PWord; fRelR: PSingle; fRelB: PSingle; info: WhiteBalanceInfo): integer; stdcall;

	  function OA_Initialize(pcFilename: PChar; uiFileNameLen: Integer): integer; stdcall;
	  function OA_EnableMode(pcModeName: PChar): integer; stdcall;
	  function OA_GetModeAcqParams(pcModeName: PChar; ppcListOfParams: Byte): integer; stdcall;
	  function OA_GetUserModeNames(ppcListOfModes: Byte): integer; stdcall;
	  function OA_GetPreSetModeNames(ppcListOfModes: Byte): integer; stdcall;
	  function OA_GetNumberOfUserModes(puiNumberOfModes: PInteger): integer; stdcall;
	  function OA_GetNumberOfPreSetModes(puiNumberOfModes: PInteger): integer; stdcall;
	  function OA_GetNumberOfAcqParams(pcModeName: PChar; puiNumberOfParams: PInteger): integer; stdcall;
	  function OA_AddMode(pcModeName: PChar; uiModeNameLen: Integer; pcModeDescription: PChar; uiModeDescriptionLen: Integer): integer; stdcall;
	  function OA_WriteToFile(pcFileName: PChar; uiFileNameLen: Integer): integer; stdcall;
	  function OA_DeleteMode(pcModeName: PChar; uiModeNameLen: Integer): integer; stdcall;
	  function OA_SetInt(pcModeName: PChar; pcModeParam: PChar; iIntValue: Integer): integer; stdcall;
	  function OA_SetFloat(pcModeName: PChar; pcModeParam: PChar; fFloatValue: Single): integer; stdcall;
	  function OA_SetString(pcModeName: PChar; pcModeParam: PChar; pcStringValue: PChar; uiStringLen: Integer): integer; stdcall;
	  function OA_GetInt(pcModeName: PChar; pcModeParam: PChar; iIntValue: PInteger): integer; stdcall;
	  function OA_GetFloat(pcModeName: PChar; pcModeParam: PChar; fFloatValue: PSingle): integer; stdcall;
	  function OA_GetString(pcModeName: PChar; pcModeParam: PChar; pcStringValue: PChar; uiStringLen: Integer): integer; stdcall;

implementation
		
	  function AbortAcquisition; external 'atmcd32d.dll' name 'AbortAcquisition';
	  function CancelWait; external 'atmcd32d.dll' name 'CancelWait';
	  function CoolerOFF; external 'atmcd32d.dll' name 'CoolerOFF';
	  function CoolerON; external 'atmcd32d.dll' name 'CoolerON';
	  function DemosaicImage; external 'atmcd32d.dll' name 'DemosaicImage';
	  function EnableKeepCleans; external 'atmcd32d.dll' name 'EnableKeepCleans';
	  function FreeInternalMemory; external 'atmcd32d.dll' name 'FreeInternalMemory';
	  function GetAcquiredData; external 'atmcd32d.dll' name 'GetAcquiredData';
	  function GetAcquiredData16; external 'atmcd32d.dll' name 'GetAcquiredData16';
	  function GetAcquiredFloatData; external 'atmcd32d.dll' name 'GetAcquiredFloatData';
	  function GetAcquisitionProgress; external 'atmcd32d.dll' name 'GetAcquisitionProgress';
	  function GetAcquisitionTimings; external 'atmcd32d.dll' name 'GetAcquisitionTimings';
	  function GetAdjustedRingExposureTimes; external 'atmcd32d.dll' name 'GetAdjustedRingExposureTimes';
	  function GetAllDMAData; external 'atmcd32d.dll' name 'GetAllDMAData';
	  function GetAmpDesc; external 'atmcd32d.dll' name 'GetAmpDesc';
	  function GetAmpMaxSpeed; external 'atmcd32d.dll' name 'GetAmpMaxSpeed';
	  function GetAvailableCameras; external 'atmcd32d.dll' name 'GetAvailableCameras';
	  function GetBackground; external 'atmcd32d.dll' name 'GetBackground';
	  function GetBitDepth; external 'atmcd32d.dll' name 'GetBitDepth';
	  function GetCameraEventStatus; external 'atmcd32d.dll' name 'GetCameraEventStatus';
	  function GetCameraHandle; external 'atmcd32d.dll' name 'GetCameraHandle';
	  function GetCameraInformation; external 'atmcd32d.dll' name 'GetCameraInformation';
	  function GetCameraSerialNumber; external 'atmcd32d.dll' name 'GetCameraSerialNumber';
	  function GetCapabilities; external 'atmcd32d.dll' name 'GetCapabilities';
	  function GetControllerCardModel; external 'atmcd32d.dll' name 'GetControllerCardModel';
	  function GetCurrentCamera; external 'atmcd32d.dll' name 'GetCurrentCamera';
	  function GetCYMGShift; external 'atmcd32d.dll' name 'GetCYMGShift';
	  function GetDDGExternalOutputEnabled; external 'atmcd32d.dll' name 'GetDDGExternalOutputEnabled';
	  function GetDDGExternalOutputPolarity; external 'atmcd32d.dll' name 'GetDDGExternalOutputPolarity';
	  function GetDDGExternalOutputStepEnabled; external 'atmcd32d.dll' name 'GetDDGExternalOutputStepEnabled';
	  function GetDDGExternalOutputTime; external 'atmcd32d.dll' name 'GetDDGExternalOutputTime';
	  function GetDDGGateTime; external 'atmcd32d.dll' name 'GetDDGGateTime';
	  function GetDDGInsertionDelay; external 'atmcd32d.dll' name 'GetDDGInsertionDelay';
	  function GetDDGIntelligate; external 'atmcd32d.dll' name 'GetDDGIntelligate';
	  function GetDDGIOC; external 'atmcd32d.dll' name 'GetDDGIOC';
	  function GetDDGIOCFrequency; external 'atmcd32d.dll' name 'GetDDGIOCFrequency';
	  function GetDDGIOCNumber; external 'atmcd32d.dll' name 'GetDDGIOCNumber';
	  function GetDDGIOCNumberRequested; external 'atmcd32d.dll' name 'GetDDGIOCNumberRequested';
	  function GetDDGIOCPeriod; external 'atmcd32d.dll' name 'GetDDGIOCPeriod';
	  function GetDDGIOCPulses; external 'atmcd32d.dll' name 'GetDDGIOCPulses';
	  function GetDDGLiteGlobalControlByte; external 'atmcd32d.dll' name 'GetDDGLiteGlobalControlByte';
	  function GetDDGLiteControlByte; external 'atmcd32d.dll' name 'GetDDGLiteControlByte';
	  function GetDDGLiteInitialDelay; external 'atmcd32d.dll' name 'GetDDGLiteInitialDelay';
	  function GetDDGLitePulseWidth; external 'atmcd32d.dll' name 'GetDDGLitePulseWidth';
	  function GetDDGLiteInterPulseDelay; external 'atmcd32d.dll' name 'GetDDGLiteInterPulseDelay';
	  function GetDDGLitePulsesPerExposure; external 'atmcd32d.dll' name 'GetDDGLitePulsesPerExposure';
	  function GetDDGPulse; external 'atmcd32d.dll' name 'GetDDGPulse';
	  function GetDDGStepCoefficients; external 'atmcd32d.dll' name 'GetDDGStepCoefficients';
	  function GetDDGStepMode; external 'atmcd32d.dll' name 'GetDDGStepMode';
	  function GetDetector; external 'atmcd32d.dll' name 'GetDetector';
	  function GetDICameraInfo; external 'atmcd32d.dll' name 'GetDICameraInfo';
	  function GetEMCCDGain; external 'atmcd32d.dll' name 'GetEMCCDGain';
	  function GetEMGainRange; external 'atmcd32d.dll' name 'GetEMGainRange';
	  function GetExternalTriggerTermination; external 'atmcd32d.dll' name 'GetExternalTriggerTermination';
	  function GetFastestRecommendedVSSpeed; external 'atmcd32d.dll' name 'GetFastestRecommendedVSSpeed';
	  function GetFIFOUsage; external 'atmcd32d.dll' name 'GetFIFOUsage';
	  function GetFilterMode; external 'atmcd32d.dll' name 'GetFilterMode';
	  function GetFKExposureTime; external 'atmcd32d.dll' name 'GetFKExposureTime';
	  function GetFKVShiftSpeed; external 'atmcd32d.dll' name 'GetFKVShiftSpeed';
	  function GetFKVShiftSpeedF; external 'atmcd32d.dll' name 'GetFKVShiftSpeedF';
	  function GetFrontEndStatus; external 'atmcd32d.dll' name 'GetFrontEndStatus';
	  function GetGateMode; external 'atmcd32d.dll' name 'GetGateMode';
	  function GetHardwareVersion; external 'atmcd32d.dll' name 'GetHardwareVersion';
	  function GetHeadModel; external 'atmcd32d.dll' name 'GetHeadModel';
	  function GetHorizontalSpeed; external 'atmcd32d.dll' name 'GetHorizontalSpeed';
	  function GetHSSpeed; external 'atmcd32d.dll' name 'GetHSSpeed';
	  function GetHVflag; external 'atmcd32d.dll' name 'GetHVflag';
	  function GetID; external 'atmcd32d.dll' name 'GetID';
	  function GetImageFlip; external 'atmcd32d.dll' name 'GetImageFlip';
	  function GetImageRotate; external 'atmcd32d.dll' name 'GetImageRotate';
	  function GetImages; external 'atmcd32d.dll' name 'GetImages';
	  function GetImages16; external 'atmcd32d.dll' name 'GetImages16';
	  function GetImagesPerDMA; external 'atmcd32d.dll' name 'GetImagesPerDMA';
	  function GetIRQ; external 'atmcd32d.dll' name 'GetIRQ';
	  function GetKeepCleanTime; external 'atmcd32d.dll' name 'GetKeepCleanTime';
	  function GetMaximumBinning; external 'atmcd32d.dll' name 'GetMaximumBinning';
	  function GetMaximumExposure; external 'atmcd32d.dll' name 'GetMaximumExposure';
	  function GetMCPGain; external 'atmcd32d.dll' name 'GetMCPGain';
	  function GetMCPGainRange; external 'atmcd32d.dll' name 'GetMCPGainRange';
	  function GetMCPGainTable; external 'atmcd32d.dll' name 'GetMCPGainTable';
	  function GetMCPVoltage; external 'atmcd32d.dll' name 'GetMCPVoltage';
	  function GetMinimumImageLength; external 'atmcd32d.dll' name 'GetMinimumImageLength';
	  function GetMinimumNumberInSeries; external 'atmcd32d.dll' name 'GetMinimumNumberInSeries';
	  function GetMostRecentColorImage16; external 'atmcd32d.dll' name 'GetMostRecentColorImage16';
	  function GetMostRecentImage; external 'atmcd32d.dll' name 'GetMostRecentImage';
	  function GetMostRecentImage16; external 'atmcd32d.dll' name 'GetMostRecentImage16';
	  function GetMSTimingsData; external 'atmcd32d.dll' name 'GetMSTimingsData';
	  function GetMetaDataInfo; external 'atmcd32d.dll' name 'GetMetaDataInfo';
	  function GetMSTimingsEnabled; external 'atmcd32d.dll' name 'GetMSTimingsEnabled';
	  function GetNewData; external 'atmcd32d.dll' name 'GetNewData';
	  function GetNewData16; external 'atmcd32d.dll' name 'GetNewData16';
	  function GetNewData8; external 'atmcd32d.dll' name 'GetNewData8';
	  function GetNewFloatData; external 'atmcd32d.dll' name 'GetNewFloatData';
	  function GetNumberADChannels; external 'atmcd32d.dll' name 'GetNumberADChannels';
	  function GetNumberAmp; external 'atmcd32d.dll' name 'GetNumberAmp';
	  function GetNumberAvailableImages; external 'atmcd32d.dll' name 'GetNumberAvailableImages';
	  function GetNumberDDGExternalOutputs; external 'atmcd32d.dll' name 'GetNumberDDGExternalOutputs';
	  function GetNumberDevices; external 'atmcd32d.dll' name 'GetNumberDevices';
	  function GetNumberFKVShiftSpeeds; external 'atmcd32d.dll' name 'GetNumberFKVShiftSpeeds';
	  function GetNumberHorizontalSpeeds; external 'atmcd32d.dll' name 'GetNumberHorizontalSpeeds';
	  function GetNumberHSSpeeds; external 'atmcd32d.dll' name 'GetNumberHSSpeeds';
	  function GetNumberNewImages; external 'atmcd32d.dll' name 'GetNumberNewImages';
	  function GetNumberPreAmpGains; external 'atmcd32d.dll' name 'GetNumberPreAmpGains';
	  function GetNumberRingExposureTimes; external 'atmcd32d.dll' name 'GetNumberRingExposureTimes';
	  function GetNumberIO; external 'atmcd32d.dll' name 'GetNumberIO';
	  function GetNumberVerticalSpeeds; external 'atmcd32d.dll' name 'GetNumberVerticalSpeeds';
	  function GetNumberVSAmplitudes; external 'atmcd32d.dll' name 'GetNumberVSAmplitudes';
	  function GetNumberVSSpeeds; external 'atmcd32d.dll' name 'GetNumberVSSpeeds';
	  function GetOldestImage; external 'atmcd32d.dll' name 'GetOldestImage';
	  function GetOldestImage16; external 'atmcd32d.dll' name 'GetOldestImage16';
	  function GetPhosphorStatus; external 'atmcd32d.dll' name 'GetPhosphorStatus';
	  function GetPhysicalDMAAddress; external 'atmcd32d.dll' name 'GetPhysicalDMAAddress';
	  function GetPixelSize; external 'atmcd32d.dll' name 'GetPixelSize';
	  function GetPreAmpGain; external 'atmcd32d.dll' name 'GetPreAmpGain';
	  function GetDualExposureTimes; external 'atmcd32d.dll' name 'GetDualExposureTimes';
	  function GetQE; external 'atmcd32d.dll' name 'GetQE';
	  function GetReadOutTime; external 'atmcd32d.dll' name 'GetReadOutTime';
	  function GetRegisterDump; external 'atmcd32d.dll' name 'GetRegisterDump';
	  function GetRingExposureRange; external 'atmcd32d.dll' name 'GetRingExposureRange';
	  function GetSensitivity; external 'atmcd32d.dll' name 'GetSensitivity';
	  function GetSizeOfCircularBuffer; external 'atmcd32d.dll' name 'GetSizeOfCircularBuffer';
	  function GetSlotBusDeviceFunction; external 'atmcd32d.dll' name 'GetSlotBusDeviceFunction';
	  function GetSoftwareVersion; external 'atmcd32d.dll' name 'GetSoftwareVersion';
	  function GetSpoolProgress; external 'atmcd32d.dll' name 'GetSpoolProgress';
	  function GetStartUpTime; external 'atmcd32d.dll' name 'GetStartUpTime';
	  function GetStatus; external 'atmcd32d.dll' name 'GetStatus';
	  function GetTECStatus; external 'atmcd32d.dll' name 'GetTECStatus';
	  function GetTemperature; external 'atmcd32d.dll' name 'GetTemperature';
	  function GetTemperatureF; external 'atmcd32d.dll' name 'GetTemperatureF';
	  function GetTemperatureRange; external 'atmcd32d.dll' name 'GetTemperatureRange';
	  function GetTemperatureStatus; external 'atmcd32d.dll' name 'GetTemperatureStatus';
	  function GetTotalNumberImagesAcquired; external 'atmcd32d.dll' name 'GetTotalNumberImagesAcquired';
	  function GetIODirection; external 'atmcd32d.dll' name 'GetIODirection';
	  function GetIOLevel; external 'atmcd32d.dll' name 'GetIOLevel';
	  function GetVersionInfo; external 'atmcd32d.dll' name 'GetVersionInfo';
	  function GetVerticalSpeed; external 'atmcd32d.dll' name 'GetVerticalSpeed';
	  function GetVirtualDMAAddress; external 'atmcd32d.dll' name 'GetVirtualDMAAddress';
	  function GetVSSpeed; external 'atmcd32d.dll' name 'GetVSSpeed';
	  function GPIBReceive; external 'atmcd32d.dll' name 'GPIBReceive';
	  function GPIBSend; external 'atmcd32d.dll' name 'GPIBSend';
	  function I2CBurstRead; external 'atmcd32d.dll' name 'I2CBurstRead';
	  function I2CBurstWrite; external 'atmcd32d.dll' name 'I2CBurstWrite';
	  function I2CRead; external 'atmcd32d.dll' name 'I2CRead';
	  function I2CReset; external 'atmcd32d.dll' name 'I2CReset';
	  function I2CWrite; external 'atmcd32d.dll' name 'I2CWrite';
	  function IdAndorDll; external 'atmcd32d.dll' name 'IdAndorDll';
	  function InAuxPort; external 'atmcd32d.dll' name 'InAuxPort';
	  function Initialize; external 'atmcd32d.dll' name 'Initialize';
	  function InitializeDevice; external 'atmcd32d.dll' name 'InitializeDevice';
	  function IsAmplifierAvailable; external 'atmcd32d.dll' name 'IsAmplifierAvailable';
	  function IsCoolerOn; external 'atmcd32d.dll' name 'IsCoolerOn';
	  function IsInternalMechanicalShutter; external 'atmcd32d.dll' name 'IsInternalMechanicalShutter';
	  function IsPreAmpGainAvailable; external 'atmcd32d.dll' name 'IsPreAmpGainAvailable';
	  function IsTriggerModeAvailable; external 'atmcd32d.dll' name 'IsTriggerModeAvailable';
	  function Merge; external 'atmcd32d.dll' name 'Merge';
	  function OutAuxPort; external 'atmcd32d.dll' name 'OutAuxPort';
	  function PrepareAcquisition; external 'atmcd32d.dll' name 'PrepareAcquisition';
	  function SaveAsBmp; external 'atmcd32d.dll' name 'SaveAsBmp';
	  function SaveAsCommentedSif; external 'atmcd32d.dll' name 'SaveAsCommentedSif';
	  function SaveAsEDF; external 'atmcd32d.dll' name 'SaveAsEDF';
	  function SaveAsFITS; external 'atmcd32d.dll' name 'SaveAsFITS';
	  function SaveAsRaw; external 'atmcd32d.dll' name 'SaveAsRaw';
	  function SaveAsSif; external 'atmcd32d.dll' name 'SaveAsSif';
	  function SaveAsSPC; external 'atmcd32d.dll' name 'SaveAsSPC';
	  function SaveAsTiff; external 'atmcd32d.dll' name 'SaveAsTiff';
	  function SaveAsTiffEx; external 'atmcd32d.dll' name 'SaveAsTiffEx';
	  function SaveEEPROMToFile; external 'atmcd32d.dll' name 'SaveEEPROMToFile';
	  function SaveToClipBoard; external 'atmcd32d.dll' name 'SaveToClipBoard';
	  function SelectDevice; external 'atmcd32d.dll' name 'SelectDevice';
	  function SendSoftwareTrigger; external 'atmcd32d.dll' name 'SendSoftwareTrigger';
	  function SetAccumulationCycleTime; external 'atmcd32d.dll' name 'SetAccumulationCycleTime';
	  function SetAcqStatusEvent; external 'atmcd32d.dll' name 'SetAcqStatusEvent';
	  function SetAcquisitionMode; external 'atmcd32d.dll' name 'SetAcquisitionMode';
	  function SetAcquisitionType; external 'atmcd32d.dll' name 'SetAcquisitionType';
	  function SetADChannel; external 'atmcd32d.dll' name 'SetADChannel';
	  function SetAdvancedTriggerModeState; external 'atmcd32d.dll' name 'SetAdvancedTriggerModeState';
	  function SetBackground; external 'atmcd32d.dll' name 'SetBackground';
	  function SetBaselineClamp; external 'atmcd32d.dll' name 'SetBaselineClamp';
	  function SetBaselineOffset; external 'atmcd32d.dll' name 'SetBaselineOffset';
	  function SetCameraStatusEnable; external 'atmcd32d.dll' name 'SetCameraStatusEnable';
	  function SetComplexImage; external 'atmcd32d.dll' name 'SetComplexImage';
	  function SetCoolerMode; external 'atmcd32d.dll' name 'SetCoolerMode';
	  function SetCountConvertMode; external 'atmcd32d.dll' name 'SetCountConvertMode';
	  function SetCountConvertWavelength; external 'atmcd32d.dll' name 'SetCountConvertWavelength';
	  function SetCropMode; external 'atmcd32d.dll' name 'SetCropMode';
	  function SetCurrentCamera; external 'atmcd32d.dll' name 'SetCurrentCamera';
	  function SetCustomTrackHBin; external 'atmcd32d.dll' name 'SetCustomTrackHBin';
	  function SetDataType; external 'atmcd32d.dll' name 'SetDataType';
	  function SetDACOutput; external 'atmcd32d.dll' name 'SetDACOutput';
	  function SetDACOutputScale; external 'atmcd32d.dll' name 'SetDACOutputScale';
	  function SetDDGAddress; external 'atmcd32d.dll' name 'SetDDGAddress';
	  function SetDDGExternalOutputEnabled; external 'atmcd32d.dll' name 'SetDDGExternalOutputEnabled';
	  function SetDDGExternalOutputPolarity; external 'atmcd32d.dll' name 'SetDDGExternalOutputPolarity';
	  function SetDDGExternalOutputStepEnabled; external 'atmcd32d.dll' name 'SetDDGExternalOutputStepEnabled';
	  function SetDDGExternalOutputTime; external 'atmcd32d.dll' name 'SetDDGExternalOutputTime';
	  function SetDDGGain; external 'atmcd32d.dll' name 'SetDDGGain';
	  function SetDDGGateStep; external 'atmcd32d.dll' name 'SetDDGGateStep';
	  function SetDDGGateTime; external 'atmcd32d.dll' name 'SetDDGGateTime';
	  function SetDDGInsertionDelay; external 'atmcd32d.dll' name 'SetDDGInsertionDelay';
	  function SetDDGIntelligate; external 'atmcd32d.dll' name 'SetDDGIntelligate';
	  function SetDDGIOC; external 'atmcd32d.dll' name 'SetDDGIOC';
	  function SetDDGIOCFrequency; external 'atmcd32d.dll' name 'SetDDGIOCFrequency';
	  function SetDDGIOCNumber; external 'atmcd32d.dll' name 'SetDDGIOCNumber';
	  function SetDDGIOCPeriod; external 'atmcd32d.dll' name 'SetDDGIOCPeriod';
	  function SetDDGLiteGlobalControlByte; external 'atmcd32d.dll' name 'SetDDGLiteGlobalControlByte';
	  function SetDDGLiteControlByte; external 'atmcd32d.dll' name 'SetDDGLiteControlByte';
	  function SetDDGLiteInitialDelay; external 'atmcd32d.dll' name 'SetDDGLiteInitialDelay';
	  function SetDDGLitePulseWidth; external 'atmcd32d.dll' name 'SetDDGLitePulseWidth';
	  function SetDDGLiteInterPulseDelay; external 'atmcd32d.dll' name 'SetDDGLiteInterPulseDelay';
	  function SetDDGLitePulsesPerExposure; external 'atmcd32d.dll' name 'SetDDGLitePulsesPerExposure';
	  function SetDDGStepCoefficients; external 'atmcd32d.dll' name 'SetDDGStepCoefficients';
	  function SetDDGStepMode; external 'atmcd32d.dll' name 'SetDDGStepMode';
	  function SetDDGTimes; external 'atmcd32d.dll' name 'SetDDGTimes';
	  function SetDDGTriggerMode; external 'atmcd32d.dll' name 'SetDDGTriggerMode';
	  function SetDDGVariableGateStep; external 'atmcd32d.dll' name 'SetDDGVariableGateStep';
	  function SetDelayGenerator; external 'atmcd32d.dll' name 'SetDelayGenerator';
	  function SetDMAParameters; external 'atmcd32d.dll' name 'SetDMAParameters';
	  function SetDriverEvent; external 'atmcd32d.dll' name 'SetDriverEvent';
	  function SetEMAdvanced; external 'atmcd32d.dll' name 'SetEMAdvanced';
	  function SetEMCCDGain; external 'atmcd32d.dll' name 'SetEMCCDGain';
	  function SetEMClockCompensation; external 'atmcd32d.dll' name 'SetEMClockCompensation';
	  function SetEMGainMode; external 'atmcd32d.dll' name 'SetEMGainMode';
	  function SetExposureTime; external 'atmcd32d.dll' name 'SetExposureTime';
	  function SetExternalTriggerTermination; external 'atmcd32d.dll' name 'SetExternalTriggerTermination';
	  function SetFanMode; external 'atmcd32d.dll' name 'SetFanMode';
	  function SetFastExtTrigger; external 'atmcd32d.dll' name 'SetFastExtTrigger';
	  function SetFastKinetics; external 'atmcd32d.dll' name 'SetFastKinetics';
	  function SetFastKineticsEx; external 'atmcd32d.dll' name 'SetFastKineticsEx';
	  function SetFilterMode; external 'atmcd32d.dll' name 'SetFilterMode';
	  function SetFilterParameters; external 'atmcd32d.dll' name 'SetFilterParameters';
	  function SetFKVShiftSpeed; external 'atmcd32d.dll' name 'SetFKVShiftSpeed';
	  function SetFPDP; external 'atmcd32d.dll' name 'SetFPDP';
	  function SetFrameTransferMode; external 'atmcd32d.dll' name 'SetFrameTransferMode';
	  function SetFrontEndEvent; external 'atmcd32d.dll' name 'SetFrontEndEvent';
	  function SetFullImage; external 'atmcd32d.dll' name 'SetFullImage';
	  function SetFVBHBin; external 'atmcd32d.dll' name 'SetFVBHBin';
	  function SetGain; external 'atmcd32d.dll' name 'SetGain';
	  function SetGate; external 'atmcd32d.dll' name 'SetGate';
	  function SetGateMode; external 'atmcd32d.dll' name 'SetGateMode';
	  function SetHighCapacity; external 'atmcd32d.dll' name 'SetHighCapacity';
	  function SetHorizontalSpeed; external 'atmcd32d.dll' name 'SetHorizontalSpeed';
	  function SetHSSpeed; external 'atmcd32d.dll' name 'SetHSSpeed';
	  function SetImage; external 'atmcd32d.dll' name 'SetImage';
	  function SetImageFlip; external 'atmcd32d.dll' name 'SetImageFlip';
	  function SetImageRotate; external 'atmcd32d.dll' name 'SetImageRotate';
	  function SetIsolatedCropMode; external 'atmcd32d.dll' name 'SetIsolatedCropMode';
	  function SetKineticCycleTime; external 'atmcd32d.dll' name 'SetKineticCycleTime';
	  function SetMCPGain; external 'atmcd32d.dll' name 'SetMCPGain';
	  function SetMCPGating; external 'atmcd32d.dll' name 'SetMCPGating';
	  function SetMessageWindow; external 'atmcd32d.dll' name 'SetMessageWindow';
	  function SetMetaData; external 'atmcd32d.dll' name 'SetMetaData';
	  function SetMultiTrack; external 'atmcd32d.dll' name 'SetMultiTrack';
	  function SetMultiTrackHBin; external 'atmcd32d.dll' name 'SetMultiTrackHBin';
	  function SetMultiTrackHRange; external 'atmcd32d.dll' name 'SetMultiTrackHRange';
	  function SetMultiTrackScan; external 'atmcd32d.dll' name 'SetMultiTrackScan';
	  function SetNextAddress; external 'atmcd32d.dll' name 'SetNextAddress';
	  function SetNextAddress16; external 'atmcd32d.dll' name 'SetNextAddress16';
	  function SetNumberAccumulations; external 'atmcd32d.dll' name 'SetNumberAccumulations';
	  function SetNumberKinetics; external 'atmcd32d.dll' name 'SetNumberKinetics';
	  function SetNumberPrescans; external 'atmcd32d.dll' name 'SetNumberPrescans';
	  function SetOutputAmplifier; external 'atmcd32d.dll' name 'SetOutputAmplifier';
	  function SetOverlapMode; external 'atmcd32d.dll' name 'SetOverlapMode';
	  function SetPCIMode; external 'atmcd32d.dll' name 'SetPCIMode';
	  function SetPhotonCounting; external 'atmcd32d.dll' name 'SetPhotonCounting';
	  function SetPhotonCountingThreshold; external 'atmcd32d.dll' name 'SetPhotonCountingThreshold';
	  function SetPhosphorEvent; external 'atmcd32d.dll' name 'SetPhosphorEvent';
	  function SetPhotonCountingDivisions; external 'atmcd32d.dll' name 'SetPhotonCountingDivisions';
	  function SetPixelMode; external 'atmcd32d.dll' name 'SetPixelMode';
	  function SetPreAmpGain; external 'atmcd32d.dll' name 'SetPreAmpGain';
	  function SetDualExposureTimes; external 'atmcd32d.dll' name 'SetDualExposureTimes';
	  function SetDualExposureMode; external 'atmcd32d.dll' name 'SetDualExposureMode';
	  function SetRandomTracks; external 'atmcd32d.dll' name 'SetRandomTracks';
	  function SetReadMode; external 'atmcd32d.dll' name 'SetReadMode';
	  function SetRegisterDump; external 'atmcd32d.dll' name 'SetRegisterDump';
	  function SetRingExposureTimes; external 'atmcd32d.dll' name 'SetRingExposureTimes';
	  function SetSaturationEvent; external 'atmcd32d.dll' name 'SetSaturationEvent';
	  function SetShutter; external 'atmcd32d.dll' name 'SetShutter';
	  function SetShutterEx; external 'atmcd32d.dll' name 'SetShutterEx';
	  function SetShutters; external 'atmcd32d.dll' name 'SetShutters';
	  function SetSifComment; external 'atmcd32d.dll' name 'SetSifComment';
	  function SetSingleTrack; external 'atmcd32d.dll' name 'SetSingleTrack';
	  function SetSingleTrackHBin; external 'atmcd32d.dll' name 'SetSingleTrackHBin';
	  function SetSpool; external 'atmcd32d.dll' name 'SetSpool';
	  function SetStorageMode; external 'atmcd32d.dll' name 'SetStorageMode';
	  function SetTECEvent; external 'atmcd32d.dll' name 'SetTECEvent';
	  function SetTemperature; external 'atmcd32d.dll' name 'SetTemperature';
	  function SetTemperatureEvent; external 'atmcd32d.dll' name 'SetTemperatureEvent';
	  function SetTriggerMode; external 'atmcd32d.dll' name 'SetTriggerMode';
	  function SetTriggerInvert; external 'atmcd32d.dll' name 'SetTriggerInvert';
	  function GetTriggerLevelRange; external 'atmcd32d.dll' name 'GetTriggerLevelRange';
	  function SetTriggerLevel; external 'atmcd32d.dll' name 'SetTriggerLevel';
	  function SetIODirection; external 'atmcd32d.dll' name 'SetIODirection';
	  function SetIOLevel; external 'atmcd32d.dll' name 'SetIOLevel';
	  function SetUserEvent; external 'atmcd32d.dll' name 'SetUserEvent';
	  function SetUSGenomics; external 'atmcd32d.dll' name 'SetUSGenomics';
	  function SetVerticalRowBuffer; external 'atmcd32d.dll' name 'SetVerticalRowBuffer';
	  function SetVerticalSpeed; external 'atmcd32d.dll' name 'SetVerticalSpeed';
	  function SetVirtualChip; external 'atmcd32d.dll' name 'SetVirtualChip';
	  function SetVSAmplitude; external 'atmcd32d.dll' name 'SetVSAmplitude';
	  function SetVSSpeed; external 'atmcd32d.dll' name 'SetVSSpeed';
	  function ShutDown; external 'atmcd32d.dll' name 'ShutDown';
	  function StartAcquisition; external 'atmcd32d.dll' name 'StartAcquisition';
	  function UnMapPhysicalAddress; external 'atmcd32d.dll' name 'UnMapPhysicalAddress';
	  function WaitForAcquisition; external 'atmcd32d.dll' name 'WaitForAcquisition';
	  function WaitForAcquisitionByHandle; external 'atmcd32d.dll' name 'WaitForAcquisitionByHandle';
	  function WaitForAcquisitionByHandleTimeOut; external 'atmcd32d.dll' name 'WaitForAcquisitionByHandleTimeOut';
	  function WaitForAcquisitionTimeOut; external 'atmcd32d.dll' name 'WaitForAcquisitionTimeOut';
	  function WhiteBalance; external 'atmcd32d.dll' name 'WhiteBalance';
	  function OA_Initialize; external 'atmcd32d.dll' name 'OA_Initialize';
	  function OA_EnableMode; external 'atmcd32d.dll' name 'OA_EnableMode';
	  function OA_GetModeAcqParams; external 'atmcd32d.dll' name 'OA_GetModeAcqParams';
	  function OA_GetUserModeNames; external 'atmcd32d.dll' name 'OA_GetUserModeNames';
	  function OA_GetPreSetModeNames; external 'atmcd32d.dll' name 'OA_GetPreSetModeNames';
	  function OA_GetNumberOfUserModes; external 'atmcd32d.dll' name 'OA_GetNumberOfUserModes';
	  function OA_GetNumberOfPreSetModes; external 'atmcd32d.dll' name 'OA_GetNumberOfPreSetModes';
	  function OA_GetNumberOfAcqParams; external 'atmcd32d.dll' name 'OA_GetNumberOfAcqParams';
	  function OA_AddMode; external 'atmcd32d.dll' name 'OA_AddMode';
	  function OA_WriteToFile; external 'atmcd32d.dll' name 'OA_WriteToFile';
	  function OA_DeleteMode; external 'atmcd32d.dll' name 'OA_DeleteMode';
	  function OA_SetInt; external 'atmcd32d.dll' name 'OA_SetInt';
	  function OA_SetFloat; external 'atmcd32d.dll' name 'OA_SetFloat';
	  function OA_SetString; external 'atmcd32d.dll' name 'OA_SetString';
	  function OA_GetInt; external 'atmcd32d.dll' name 'OA_GetInt';
	  function OA_GetFloat; external 'atmcd32d.dll' name 'OA_GetFloat';
	  function OA_GetString; external 'atmcd32d.dll' name 'OA_GetString';
end.
